include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: false # Allowing print for basic debugging in this MVP
    use_build_context_synchronously: false
